# ======== Signup ========

# POST http://localhost:9001/api/v1/auth/signup
# Content-Type: application/json

# {
#     "email": "liviya@example.com",
#     "password": "Hello123",
#     "fullName": "Liviya"
# }


# ======== Signin ========

# POST http://localhost:9001/api/v1/auth/signin
# Content-Type: application/json

# {
#     "email": "liviya@example.com",
#     "password": "Hello123"
# }


# ======== Get Upload URL ========

# GET http://localhost:9001/api/v1/blogs/get-upload-url


# ======== Crete Blog ========

# POST http://localhost:9001/api/v1/blogs/create
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTEwMjRiODExNDhmZWFkZGYxMzFiMCIsImlhdCI6MTY5OTgwNzgxOX0.n8Dw7Jj_ENMtE3JESLdp6V4V0TaZVfcD9_PM3PSIFTg

# {
#     "title": "New Hello",
#     "banner": "http://example.com/a.png",
#     "des": "Hellooooo",
#     "content": {
#         "blocks": [1, 2]
#     },
#     "tags": ["aa", "bb"]
# }

# =========== Latest Blogs && Trending Blogs =========

# GET http://localhost:9001/api/v1/blogs/trending

# ========= Search Blog =============

# POST http://localhost:9001/api/v1/blogs/search
# Content-Type: application/json

# {
#     "tag": "hello"
# }


# =========== Search Users ============

POST http://localhost:9001/api/v1/users/search
Content-Type: application/json

{
    "query": "mohammed"
}